bloger/bloger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bloger/home/urls.py
from django.urls import path
from . views import*

urlpatterns = [
    path('', home, name = 'home'),

    path('register/', register, name = 'register'),
    path('login/', login, name = 'login'),
    path('logout/', logout, name = 'logout'),

    path('profile/<str:username>/', profile, name = 'profile'),
    path('profile/update/<str:username>/', profile_update, name = 'profile_update'),
    path('profile/delete/<str:username>/', profile_delete, name = 'profile_delete'),

    path('blog_detail/<int:pk>/', blog_detail, name = 'blog_detail'),
    path('author/<str:username>/', blog_author, name = 'blog_author'),
    path('blog_create/', blog_create, name = 'blog_create'),
    path('blog_update/<int:pk>/', blog_update, name = 'blog_update'),
    path('blog_delete/<int:pk>/', blog_delete, name = 'blog_delete'),


    path('create_message/<str:username>/', create_msg, name = 'create_msg'),
    path('inbox/<str:username>/', inbox, name = 'inbox'),

    path('view_msg/<int:pk>/', view_msg, name = 'view_msg'),
    path('reply_message/<str:username>/', send_reply, name = 'send_reply'),
]

bloger/home/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE) 
    f_name = models.CharField(max_length=200, blank=True, null=True)
    l_name = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to='profile_model/', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s profile"
    
    @property
    def img_url(self):
        try:
            return self.image.url

        except Exception as ex:
            return '/static/images/static_profile_model/default.png'
        
        


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    total_votes = models.IntegerField(default=0)
    percentage = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}'s blog"

    class Meta:
        ordering = ['-created']

    @property
    def validation(self):
        total_votes = self.review_set.all()
        up_votes = total_votes.filter(vote_type = 'up')
        total = total_votes.count()
        percentage = (up_votes.count()/total) * 100
        self.total_votes = total
        self.percentage = percentage
        self.save()

    @property
    def users_list(self):
        lst = self.review_set.all().values_list('writer__pk', flat=True)
        return lst


class Tag(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.blog} | {self.name}"




class Review(models.Model):
    choices = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    vote_type = models.CharField(max_length=200, choices=choices)
    comment = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.blog.title} = {self.writer.username} = {self.vote_type}"



class Inbox(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    subject = models.CharField(max_length=200)
    body = models.TextField()
    is_read = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender.username} to {self.receiver.username} -> {self.subject}"
    
    class Meta:
        ordering = ['is_read', 'created']

bloger/home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from . models import Profile, Blog, Review, Inbox
from django.core.exceptions import ValidationError


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email has already taken!")
        return email




# class UserUpdateForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['username', 'email']

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        # Get the current user from the form instance
        current_user = self.instance

        # Check if email exists and doesn't belong to the current user
        if User.objects.filter(email=email).exclude(pk=current_user.pk).exists():
            raise ValidationError("This email is already in use by another account.")
        return email




class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['f_name', 'l_name', 'image']





class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'description']
    

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['vote_type', 'comment']


class InboxForm(forms.ModelForm):
    class Meta:
        model = Inbox
        fields = ['subject', 'body']

bloger/home/views.py
from django.shortcuts import render, redirect
from . forms import InboxForm, UserRegistrationForm, ProfileUpdateForm, UserUpdateForm, BlogForm, ReviewForm
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib import messages
from . models import Blog, Tag, Inbox
from .utils import searchBlog
from django.core.paginator import Paginator, PageNotAnInteger,EmptyPage

def home(request):
    # blogs = Blog.objects.all()
    blogs, query = searchBlog(request)

    result = 1
    paginator = Paginator(blogs, result)

    page = request.GET.get('page') if request.GET.get('page') else ''

    try:
        blogs = paginator.page(page)
    
    except PageNotAnInteger:
        page = '1'
        blogs = paginator.page(page)

    except EmptyPage:
        page = paginator.num_pages
        blogs = paginator.page(page)

    context = {'blogs':blogs, 'query':query}
    return render(request, 'home/index.html', context)



def register(request):
    form = UserRegistrationForm()
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            username = new_user.username
            new_user.username = username.lower()
            new_user.save()
            auth.login(request, new_user)
            messages.success(request, "User created successfully!")
            return redirect('home')
        # else:
            # messages.error(request, "Something went wrong,Try Again!")
            # return redirect('register')
    context = {'form':form}
    return render(request, 'home/register.html', context)



def login(request):
    if request.user.is_authenticated:
        messages.info(request, "You've already Loged-In!")
        return redirect('home')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        auth_user = auth.authenticate(username = username, password = password)
        if auth_user is not None:
            auth.login(request, auth_user)
            messages.success(request, "Successfully Loged-In!")
            return redirect(request.GET.get('next') if request.GET.get('next') else 'home')
        else:
            messages.error(request, "User doesn't exist!")
            return redirect('login')
    return render(request, 'home/login.html')



def logout(request):
    if not(request.user.is_authenticated):
        messages.info(request, "You've not Loged-In")
        return redirect('home')
    auth.logout(request)
    messages.success(request, "Successfully Loged-Out!")
    return redirect('home')



@login_required
def profile(request, username):
    current_user = User.objects.get(username = username)
    if current_user.username != request.user.username:
        return HttpResponse("<h1>403</h1>")
    blogs = current_user.blog_set.all()
    context = {'current_user':current_user, 'blogs':blogs}
    return render(request, 'home/profile.html', context)



@login_required
def profile_update(request,username):
    current_user = User.objects.get(username = username)
 
    if current_user.username != request.user.username:
        return HttpResponse("<h1>403</h1>")
    u_form = UserUpdateForm(instance=current_user)
    p_form = ProfileUpdateForm(instance=current_user.profile)
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=current_user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=current_user.profile)

        if u_form.is_valid() and p_form.is_valid():
            updated_user = u_form.save()
            p_form.save()
            messages.success(request, "Profile Updated Successfully !")
            return redirect('profile', username = updated_user.username)
        else:
            messages.error(request, "Something Went Wrong!")
            # return redirect('profile_update', username = current_user.username)
    context = {'current_user':current_user, 'u_form':u_form ,'p_form':p_form}
    return render(request, 'home/profile_update.html', context)



@login_required
def profile_delete(request,username):
    current_user = User.objects.get(username = username)
    if current_user.username != request.user.username:
        return HttpResponse("<h1>403</h1>")
    if request.method == 'POST':
        current_user.delete()
        messages.success(request, "Account Deleted Successfully!")
        return redirect('home')
    context = {'current_user':current_user}
    return render(request, 'home/profile_delete.html', context)


# @login_required
def blog_detail(request, pk):
    blog = Blog.objects.get(id = pk)
    form = ReviewForm()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            new_vote = form.save(commit=False)
            new_vote.blog = blog
            new_vote.writer = request.user
            new_vote.save()
            messages.success(request, "Review Added Successfully!")

            blog.validation

            return redirect('blog_detail', pk = blog.id)
    context = {'blog':blog, 'form':form}
    return render(request, 'home/blog_detail.html', context)


@login_required
def blog_create(request):
    form = BlogForm()
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.author = request.user
            new_blog.save()
            messages.success(request, "Blog created successfully!")
            return redirect('blog_detail', pk = new_blog.pk)
    context = {'form':form}
    return render(request, 'home/blog_create.html', context)


@login_required
def blog_update(request, pk):
    blog = Blog.objects.get(id=pk)
    if blog.author != request.user:
        return HttpResponse("<h1>403</h1>")
    form = BlogForm(instance=blog)
    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            alt_blog = form.save()
            messages.success(request, "Blog Updated Successfully!")
            return redirect('profile', username = blog.author.username)
    context = {'form':form}
    return render(request, 'home/blog_update.html', context)


@login_required
def blog_delete(request, pk):
    blog = Blog.objects.get(id=pk)
    if blog.author != request.user:
        return HttpResponse("<h1>403</h1>")
    if request.method == 'POST':
        blog.delete()
        messages.success(request, 'Blog Deleted Successfully!')
        return redirect('profile', username = blog.author.username)
    context = {'blog':blog}
    return render(request, 'home/blog_delete.html', context)


@login_required
def blog_author(request, username):
    author = User.objects.get(username = username)
    blogs = author.blog_set.all()
    context = {'author':author, 'blogs':blogs}
    return render(request, 'home/blog_author.html', context)


@login_required
def inbox(request, username):
    userr = User.objects.get(username = username)
    my_msgs = userr.receiver.all()
    context = {'userr':userr, 'my_msgs':my_msgs}
    return render(request, 'home/inbox_page.html', context)


@login_required
def view_msg(request, pk):
    msg = Inbox.objects.get(id = pk)
    receiver = msg.receiver
    if msg.is_read == False:
        msg.is_read = True
        msg.save()
    context = {'msg':msg, 'receiver':receiver}
    return render(request, 'home/inbox_view.html', context)


@login_required
def create_msg(request, username):
    receiver = User.objects.get(username = username)
    form = InboxForm()
    if request.method == 'POST':
        form = InboxForm(request.POST)
        if form.is_valid():
            msg = form.save(commit=False)
            msg.sender = request.user
            msg.receiver = receiver
            msg.save()
            messages.success(request, "Message sent successfully!")
            return redirect('blog_author', username = receiver.username)
    context = {'form':form, 'receiver': receiver}
    return render(request, 'home/inbox_create.html', context)


@login_required
def send_reply(request, username):
    receiver = User.objects.get(username = username)
    form = InboxForm()
    if request.method == 'POST':
        form = InboxForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.sender = request.user
            reply.receiver = receiver
            reply.save()
            messages.success(request, "Reply Added Successfully!")
            return redirect('inbox', username = request.user.username)
    context = {'form':form}
    return render(request, 'home/inbox_reply.html', context)

bloger/home/templates/home/blog_author.html
{% extends 'base.html' %}


{% block content %}

        <div style="width: 500px;
                    background-color: white;
                    padding: 20px;
                    margin: 10px auto;">
            
            <span><b>Username :- </b>{{author.username}}</span><br>
            <span><b>Enail :- </b>{{author.email}}</span><br>
            <div style="text-align: center;" >   
                <img src="{{author.profile.img_url}}" alt="author's pic" height="100px" width="100px">
            </div>
            <br>
                {% if request.user != author %}
                    <a style="background-color: aqua;
                    padding: 1em;" href="{% url 'create_msg' author.username %}">Message</a>
                {% endif %}
            <br>
        </div>

        <br><br>


        <div style="width: 450px;
        background-color: white;
        padding: 20px;
        margin: 10px auto;">

            {% for blog in blogs %}

                <div><b>Title :- </b>{{blog.title}}</div>
                <div><b>Description :- </b>{{blog.description}}</div>
                <div><b>Created :- </b>{{blog.created}}</div>

                {% for tag in blog.tag_set.all %}
                    <span>{{tag.name}}&nbsp;</span>
                {% endfor %}
                <hr>

            {% endfor %}

        </div>

{% endblock content %}

bloger/home/templates/home/blog_create.html
{% extends 'base.html' %}


{% block content %}

        <div style="width: 500px;
                    background-color: white;
                    padding: 20px;
                    margin: 10px auto;">

            <form action="" method="POST">
                {% csrf_token %}

                {{form.as_p}}

                <button type="submit">Submit</button>
            </form>

        </div>

        <br><br>




{% endblock content %}

bloger/home/templates/home/blog_delete.html
{% extends 'base.html' %}


{% block content %}

        <div style="width: 500px;
                    background-color: white;
                    padding: 20px;
                    margin: 10px auto;">

            <form action="" method="POST">
                {% csrf_token %}

                <h3>
                    Are U Sure U Want To Delete '{{blog.title}}' ?
                </h3>

                <button type="submit">Delete</button>
                &nbsp;
                <a href="{% url 'profile' blog.author.username %}">Back</a>
            </form>

        </div>

        <br><br>




{% endblock content %}

bloger/home/templates/home/blog_detail.html
{% extends 'base.html' %}


{% block content %}


        <div style="width: 450px;
        background-color: white;
        padding: 20px;
        margin: 10px auto;">

  
            <div><img src="{{blog.author.profile.img_url}}" alt="profile_pic" width="100px" height="100px"></div>
            <br>
            <div><b>Author :- </b>{{blog.author.username}}</div>
            <div><b>Title :- </b>{{blog.title}}</div>
            <div><b>Description :- </b>{{blog.description}}</div>
            <div><b>Created :- </b>{{blog.created}}</div>

            {% for tag in blog.tag_set.all %}
                <span>{{tag.name}}&nbsp;</span>
            {% endfor %}
            <br><br>

                Total Votes :- {{blog.total_votes}} Vote{{blog.total_votes|pluralize:'s'}}
                <br>
                Percentage :- {{blog.percentage}}%

            <br><br>

            {% if request.user.is_authenticated %}
                {% if request.user == blog.author %}
                    <h5>You Can't Vote On Your Own Project!</h5>
                {% elif request.user.pk in blog.users_list %}
                    <h5>You've Already Voted!</h5>
                {% else %}
                    <form action="" method="POST">
                        {% csrf_token %}

                            {{form.as_p}}
                        <button type="submit">Vote</button>
                    </form>
                {% endif %}
            {% else %}
                <h5><a href="{% url 'login' %}?next={{request.path}}">Login</a></h5>
            {% endif %}
        

        </div>

{% endblock content %}

bloger/home/templates/home/blog_update.html
{% extends 'base.html' %}


{% block content %}

        <div style="width: 500px;
                    background-color: white;
                    padding: 20px;
                    margin: 10px auto;">

            <form action="" method="POST">
                {% csrf_token %}

                {{form.as_p}}

                <button type="submit">Submit</button>
            </form>

        </div>

        <br><br>




{% endblock content %}

bloger/home/templates/home/inbox_create.html
{% extends 'base.html' %}


{% block content %}

    <div style="width: 500px; 
                background-color: white; 
                margin: 10px auto;
                padding: 20px;">

        <h1>Register</h1>
        <form action="" method="POST" autocomplete="off">
            {% csrf_token %}

            {{form.as_p}}

            <button type="submit">Submit</button>
            &nbsp; <a href="{% url 'blog_author' receiver.username %}">Back</a>

        </form>

    </div>

{% endblock content %}

bloger/home/templates/home/inbox_page.html
{% extends 'base.html' %}


{% block content %}

        <div style="width: 450px;
        background-color: white;
        padding: 20px;
        margin: 10px auto;">

            {% for msg in my_msgs %}

                Sender :- {{msg.sender.username}} <br>
                Title :- 
                    {% if msg.is_read == False %}
                        <span style="font-weight: bold;">{{msg.subject}}</span> 
                    {% else %}
                        <span>{{msg.subject}}</span> 
                    {% endif %}
                <br>
                Body:- {{msg.body}} <br>
                Created :-{{msg.created|timesince}} ago... <br>
                <br>
                <a href="{% url 'send_reply' msg.sender.username %}">Reply</a>
                &nbsp;
                <a href="{% url 'view_msg' msg.pk %}">View</a>
                <hr>
            {% endfor %}

        </div>




{% endblock content %}

bloger/home/templates/home/inbox_reply.html
{% extends 'base.html' %}


{% block content %}

    <div style="width: 500px; 
                background-color: white; 
                margin: 10px auto;
                padding: 20px;">

        <h1>Register</h1>
        <form action="" method="POST" autocomplete="off">
            {% csrf_token %}

            {{form.as_p}}

            <button type="submit">RePLY</button>
            &nbsp; <a href="{% url 'inbox' request.user.username %}">Back</a>

        </form>

    </div>

{% endblock content %}

bloger/home/templates/home/index.html
{% extends 'base.html' %}


{% block content %}

        <div style="width: 500px;
                    background-color: white;
                    padding: 20px;
                    margin: 10px auto;">
            {% if request.user.is_authenticated %}
                <h2>Welcome... {{request.user.username}}</h2>
            {% else %}
                <h2> Simply.... The best website out there!  </h2>
            {% endif %}
        </div>

        <div style="width: 500px;
                    background-color: white;
                    padding: 20px;
                    margin: 10px auto;">
            <form action="" method="GET" id="form">
                <input type="text" name="query" id="" value={{query}}>
                &nbsp;&nbsp;
                <button type="submit">Search</button>
            </form>
        </div>


        <div style="width: 450px;
        background-color: white;
        padding: 20px;
        margin: 10px auto;">

            {% for blog in blogs %}
                <div><img src="{{blog.author.profile.img_url}}" alt="profile_pic" width="100px" height="100px"></div>
                <br>
                <a href="{% url 'blog_author' blog.author.username %}"><div><b>Author :- </b>{{blog.author.username}}</div></a>
                <a href="{% url 'blog_detail' blog.pk %}"><div><b>Title :- </b>{{blog.title}}</div></a>
                <div><b>Description :- </b>{{blog.description}}</div>
                <div><b>Created :- </b>{{blog.created}}</div>

                {% for tag in blog.tag_set.all %}
                    <span>{{tag.name}}&nbsp;</span>
                {% endfor %}
                <hr>

            {% endfor %}
            <br><br>

            {% include 'paginator.html' with queryset=blogs %}

        </div>




{% endblock content %}

bloger/home/templates/home/login.html
{% extends 'base.html' %}


{% block content %}

    <div style="width: 500px; 
                background-color: white; 
                margin: 10px auto;
                padding: 20px;">

        <h1>Log-In</h1>
        <form action="" method="POST" autocomplete="off">
            {% csrf_token %}

            <Label>Username :- </Label>&nbsp;
            <input type="text" name="username" required>
            <br><br>

            <label>Password :- </label>&nbsp;
            <input type="password" name="password" required>

            <br><br>
            <button type="submit">Login</button>
            &nbsp; <a href="{% url 'register' %}">Sign Up</a>
        </form>

    </div>

{% endblock content %}

bloger/home/templates/home/profile.html
{% extends 'base.html' %}


{% block content %}

        <div style="width: 500px;
                    background-color: white;
                    padding: 20px;
                    margin: 10px auto;">
            

            <h3>Username :- {{current_user.username}}</h3>
            <h3>Email :- {{current_user.email}}</h3>

            <img src="{{current_user.profile.img_url}}" alt="" width="100px" height="100px">


            <br><br>

            <a href="{% url 'profile_update' current_user.username %}">Update</a>
            <a href="{% url 'profile_delete' current_user.username %}">Delete</a>
        </div>


        <div style="width: 450px;
        background-color: white;
        padding: 20px;
        margin: 10px auto;">

            {% for blog in blogs %}

                <div><b>Title :- </b>{{blog.title}}</div>
                <div><b>Description :- </b>{{blog.description}}</div>
                <div><b>Created :- </b>{{blog.created}}</div>

                {% for tag in blog.tag_set.all %}
                    <span>{{tag.name}}&nbsp;</span>
                {% endfor %}
                <br>

                <a href="{% url 'blog_update' blog.pk %}">Update</a>
                &nbsp;
                <a href="{% url 'blog_delete' blog.pk %}">Delete</a>
                <hr>


                

            {% endfor %}

        </div>

{% endblock content %}

bloger/home/templates/home/profile_delete.html
{% extends 'base.html' %}


{% block content %}

    <div style="width: 500px; 
                background-color: white; 
                margin: 10px auto;
                padding: 20px;">

        <h1>Log-In</h1>
        <form action="" method="POST" autocomplete="off">
            {% csrf_token %}

                Are U Sure You Want to Delete '{{current_user.username}}'s profile ???

                <button type="submit">Delete</button>
                <a href="{% url 'profile' current_user.username %}">Cancle</a>

        </form>

    </div>

{% endblock content %}

bloger/home/templates/home/profile_update.html
{% extends 'base.html' %}


{% block content %}

    <div style="width: 500px; 
                background-color: white; 
                margin: 10px auto;
                padding: 20px;">

        <h1>Log-In</h1>
        <form action="" method="POST" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}

                {{u_form.as_p}}
                {{p_form.as_p}}

                <button type="submit">Update</button>
                <a href="{% url 'profile' current_user.username %}">Cancle</a>

        </form>

    </div>

{% endblock content %}

bloger/home/templates/home/register.html
{% extends 'base.html' %}


{% block content %}

    <div style="width: 500px; 
                background-color: white; 
                margin: 10px auto;
                padding: 20px;">

        <h1>Register</h1>
        <form action="" method="POST" autocomplete="off">
            {% csrf_token %}

            {{form.as_p}}

            <button type="submit">Register</button>
            &nbsp; <a href="{% url 'login' %}">Already have an account?</a>

        </form>

    </div>

{% endblock content %}